name: CI

on:
  push:
    branches: '**' 
  pull_request:
    branches: '**'
    tags: '**'
  workflow_dispatch: {}
jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Install Dependencies
        id: install-dependencies
        run: |
          export GOPATH=~/go
          mkdir -p "${GOPATH}"
          ./build-env.sh bash -xec "$(cat <<'EOF'
            yarn install && go mod download
          EOF
          )"

      - name: Build Frontend
        id: build-frontend
        run: |
          export GOPATH=~/go
          mkdir -p "${GOPATH}"
          ./build-env.sh bash -xec "$(cat <<'EOF'
            yarn build
          EOF
          )"

      - name: Build Backend
        id: build-backend
        run: |
          export GOPATH=~/go
          mkdir -p "${GOPATH}"
          ./build-env.sh bash -xec "$(cat <<'EOF'
            yarn backend
          EOF
          )"

      - name: Build Plugin Zip
        id: build-plugin-zip
        run: |
          export GOPATH=~/go
          mkdir -p "${GOPATH}"
          ./build-env.sh bash -xec "$(cat <<'EOF'
            yarn plugin
          EOF
          )"

      - name: Run Integration Tests
        id: run-integration-tests
        run: |
          export GOPATH=~/go
          mkdir -p "${GOPATH}"
          ./build-env.sh bash -xec "$(cat <<'EOF'
            yarn integration-test
          EOF
          )"


